version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d postgres_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    container_name: quiz_web
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://my_user:1234@postgres:5432/postgres_db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  pgdata:
    driver: local